package ica_validation_tests;

import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.runner.JUnitCore;
import org.junit.runner.Result;
import org.junit.runner.RunWith;
import org.junit.runner.notification.Failure;
import org.junit.runners.Suite;

/**
 *
 * @author Difma
 */
@RunWith(Suite.class)
@Suite.SuiteClasses({ica_validation_tests.CP38.class, ica_validation_tests.CP41.class, ica_validation_tests.CP30.class, ica_validation_tests.CP35.class, ica_validation_tests.CP27.class, ica_validation_tests.CP21.class, ica_validation_tests.CP24.class, ica_validation_tests.CP29.class, ica_validation_tests.CP26.class, ica_validation_tests.CP22.class, CP33.class, ica_validation_tests.CP23.class, ica_validation_tests.CP31.class, ica_validation_tests.CP40.class, ica_validation_tests.CP42.class, ica_validation_tests.CP34.class, ica_validation_tests.CP37.class, ica_validation_tests.CP45.class, CP32.class, ica_validation_tests.CP39.class, ica_validation_tests.CP43.class, ica_validation_tests.CP28.class, ica_validation_tests.CP25.class, ica_validation_tests.CP36.class, ica_validation_tests.CP44.class})
public class ICA_Validation {

    @BeforeClass
    public static void setUpClass() throws Exception {
    }

    @AfterClass
    public static void tearDownClass() throws Exception {
    }

    @Before
    public void setUp() throws Exception {
    }

    @After
    public void tearDown() throws Exception {
    }
    
}
